### ISSUE TITLE
Which versions are compatible with which versions of Django?

### ISSUE THREAD

**Issue by ringemup** [stephrdev/django-formwizard#12]
e.g. can I run 0.6 with Django 1.2, or does that require 1.3?  Will 0.5.1 run on Django 1.3?  Etc.

**Comment by stephrdev** [comment]
0.6 is the last version which will work with Django 1.2.x but all versions below and including 0.6 should run on Django 1.3. The next release of django-formwizard will only work on Django >= 1.3 (because of the class based views dependency).

**Comment by ringemup** [comment]
Thank you.
