### ISSUE TITLE
Documentation Request: Example Accessing Other Form's Data

### ISSUE THREAD

**Issue by ringemup** [stephrdev/django-formwizard#13]
Would it be possible to add an example to the docs of how to access an earlier form's data from within the **init**() or clean() methods of a subsequent form's data?  I'm sure it's simple and I'm just missing something obvious, but I've been chasing my tail all morning trying to figure it out.

Thanks!

**Comment by stephrdev** [comment]
Please open a ticket in Django (http://code.djangoproject.com) for this change request. This app will be updated in a few days and contain the backported Django 1.4 formwizard which supersedes this app. The development will continue within Django's codebase.
