### ISSUE TITLE
Browser's back button breaks formwizard

### ISSUE THREAD

**Issue by maraujop** [stephrdev/django-formwizard#14]
Hi Stephan,

I just checked version 0.6. I installed it using pip. I have to say it still has the same bug I reported long ago:
https://github.com/stephrdev/django-formwizard/pull/5

I'm going to try to explain myself better this time. Last time I mixed too many things, I changed 2 different things at the same time using the wrong branch, bad idea :(

I have a form wizard done subclassing `SessionFormWizard`. It's got 2 different forms (2 steps). First one asks for an amount to bid on a transport, second one asks for confirmation. So if I put an amount like 25, I get to the second form, If I press browser's back button then, I return to the previous page (but no GET is addressed, so storage is not reset). So I put another amount, 23. As storage step has not been reset, it thinks I'm in the 2nd step, not true! 

So two things can happen here. First the second form validates with the data I'm sending, horror! my previous bid of 25 gets accepted! Or it doesn't validate so it shows me the second form with errors (confusing for the user), but the data from the first step didn't change.

So this is why I changed the conditional flow of `process_post_request` as you can see here:
https://github.com/maraujop/django-formwizard/blob/f1ac719c412c17e02834840f768198b9908998e7/formwizard/forms.py#L131

I've thought this problem in great detail before and the only solution I've come up with, is having a explicit parameter in the form that tell us what step we are in (other would be blocking browser's back button, but I don't like it).

This way I use `form_prev_step` as a hidden input that tells the storage what step it's in, so it can work properly. 

I hope this time looks clearer, regards
Miguel

**Comment by stephane** [comment]
I'm currently banging my head on this problem too and I've reached the same conclusion! We must explicitely set the current step in the form.

**Comment by maraujop** [comment]
@stephane That is exactly what I fixed in my fork, you can see my solution in the links I posted.

If there is no explicit information about the current step, we need a way to introspect it, maybe comparing the fields we get with the form's fields we have, but I think that's too complicated and it only avoids having a hidden input, which I don't mind.

**Comment by stephrdev** [comment]
I'm currently working on integrating the formwizard to django and fix this bug and the multiple instances of formwizard issue (https://github.com/stephrdev/django-formwizard/pull/10).

**Comment by maraujop** [comment]
@stephrdev Ok, as last time I posted my code and comments, it looked like you didn't understand the issue I was reporting, I decided the best was to explain it aside. I'm glad you understand the problem and don't hesitate in using my proposed solution to the problem if you think it fits the project.

The multiple instances of formwizard issue, was part of what I was reporting last time. I sincerely hope you can integrate formwizard into Django for version 1.4.

**Comment by stephrdev** [comment]
the formwizard was integrated into Django a few days ago. I also backported the code form Django to use the formwizard with 1.3 too. The backported code fixes this problem as far as I can reproduce the bug.

Downside of the backport and the release (which I plan to do in the next days) is a changed API. The 1.0 Release will be fully backwards incompatible. You can dig into the new code here: https://github.com/stephrdev/django-formwizard/tree/feature%2Fbackport

**Comment by maraujop** [comment]
I guess you meant to say you "cannot" reproduce the bug.

I'm looking at the code and I see you are using `wizard_prev_step` to indicate current step (as I was proposing in my branch), so that stepping back works, great.

I'm glad to see this project is getting integrated in Django, will you keep the github branch for collaborations?

**Comment by stephrdev** [comment]
The main development will be in Django's code itself. I will keep this repository up to date at least until Django 1.4 is released and maybe a bit longer.

I will merge the feature/backport branch into master soon and do a pypi release too.

**Comment by maraujop** [comment]
Well done!

You know I really appreciate the effort you've put into this project. From now on doing form wizards will be a pleasant task and not a nightmare. The branch is very clean clode and nice doc strings.

I'm not sure if you can or you are interested in doing it, but I think keeping this github repository around will help get more collaborations, as Django flow is a little restricted and harder.

Thanks!
