### ISSUE TITLE
Have multiple formset/forms in one step

### ISSUE THREAD

**Issue by gdelazzer** [stephrdev/django-formwizard#20]
Would be nice to be able to have a way to have multiple forms and formset in one step.

In the old implementation of the formwizard I was saving but not committing my formsets and stored them in my formwizard class. I was passing my formset in the context.

It seems now impossible to save the formset in the class as it seems the class is instanciated again for each step.

**Comment by stephrdev** [comment]
> It seems now impossible to save the formset in the class as it seems the class is instanciated again for each step.

Yes, because this isn't thread-safe and can lead to big problems ;-)

You could use the the storage.extra_data dictionary to store your formset data to keep the content and to revalidate the formset later.
