### ISSUE TITLE
step not passed to get_form when using NamedUrls

### ISSUE THREAD

**Issue by gdelazzer** [stephrdev/django-formwizard#21]
Hi,

I have noticed in the code of NamedUrlWizardView that you don't pass the step name to get_form.

I think it should pass it as else the only we have to know what step we are in is to use self.steps.current, which can bring some bugs. For example in my use case for the same step I need to customize get_form and get_form_initial. But in my get_form_initial I need to use get_form with data parameter to retrieve a previous form data to generate my new form. As I was using self.steps.current it would bring a recursive loop.

Would be great if it could be fixed!

Thanks

**Comment by stephrdev** [comment]
Because this repository is only a backport of the Django 1.4 formwizard, could you open a ticket on https://code.djangoproject.com/newticket and if possible attach a test to demonstrate the recursive loop/bug?

**Comment by gdelazzer** [comment]
Thanks steph, I have done that :)
