### ISSUE TITLE
Uploaded file in the previous page form is not displayed when previous button is clicked in Django 1.4

### ISSUE THREAD

**Issue by pravasi** [stephrdev/django-formwizard#35]
All the other form fileds are displayed correctly with values but a FileField  is not populated when user navigates to previous page .User has to upload the file again if he navigates to previous page.When a saved instance(instance of FieldFile instead of FileField) is edited the same file upload field is displayed correctly in the previous page.So I am confused if this is an issue with ClearableFileInput widget or FormWizard not updating the .storage.current_step to w izard_goto_step.This has been raised in http://stackoverflow.com/questions/10597021/formwizard-and-filefields-django-1-4 also

**Comment by stephrdev** [comment]
Hi, as django-formwizard isn't updated anymore (its included in Django for a while now), please open a ticket here: https://code.djangoproject.com/newticket

Thank you!
