### ISSUE TITLE
Uploaded file is lost when user navigates to previous page in Django1.4

### ISSUE THREAD

**Issue by pravasi** [stephrdev/django-formwizard#36]
All other fields retains the user entered data but a uploaded file in the FileField gets lost when user navigates to previous page I tried using SessionWizardView and NamedUrlSessionWizardView.The required field validation fails.If it is a saved instance (instance of FieldFile ) being edited ,then the field is populated.To me it looked like the storage.current_step is not getting updated with wizard_goto_step and hence the storage.get_step_files is not getting uploaded files for the previous step but the ones for the current step. This issue was also raised at http://stackoverflow.com/questions/10597021/formwizard-and-filefields-django-1-4

**Comment by stephrdev** [comment]
Hi, as django-formwizard isn't updated anymore (its included in Django for a while now), please open a ticket here: https://code.djangoproject.com/newticket

Thank you!
