### ISSUE TITLE
Requirements 

### ISSUE THREAD

**Issue by maraujop** [stephrdev/django-formwizard#4]
Hi,

Today I found your project and It's exactly what I needed, great work! I installed from github and I got an ImportError becauses of `class_based_views.base`. I'm using Django 1.2.3 and I think you should mention in your docs that latest Django 1.3 alpha is necessary to have version 0.5 working. 

I would like to ask you if you are working on adding files upload support. I might have to work at it in the future and I wouldn't want to replicate work.

Thanks, regards 
Miguel

**Comment by stephrdev** [comment]
Hi, class based views is not needed in master (only in branch feature/cbv_refactor).
File upload support is implemented but not yet documented.. but I will work on it soon.

Cheers,

**Comment by maraujop** [comment]
I just realized I was using latest branch, my fault, sorry about that.

Thanks for the so fast reply :) I'm glad that you already support files. I was actually amazed you didn't after looking at the code, that makes sense.

Cheers, thanks
Miguel
